import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import DropDown from '../components/DropDown'
import styles from '../styles/Home.module.css'
import VideoPopUp from '../components/VideoPopUp'

export default function Home() {  
  return (
    <div className={styles.container}>
      <Head>
        <title>My Hands-On</title>
        <meta name="description" content="Generated by Farhad" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <section>
          <h1>
            Welcome to Drop Down
          </h1>
          <DropDown />
        </section>
        
      </main>
    </div>
  )
}
